"""Cross-architecture exploit payload construction primitives."""

from .assembler import LLVMAssembler, llvm_triple
from .errors import (
    AddressResolutionError,
    AssemblyError,
    ConstraintError,
    MemoryAccessError,
    PayloadError,
    UnsupportedTargetError,
)
from .libc import LibcError, LibcIdentity, LibcImage
from .model import (
    Address,
    ExecutionPolicy,
    Image,
    Linkage,
    MemoryRequirement,
    Mitigations,
    Payload,
    PayloadKind,
    Permission,
    Relro,
    RuntimeLayout,
)
from .shellcode import (
    command_shellcode,
    command_source,
    exit_shellcode,
    exit_source,
    mmap_stager,
    mmap_stager_source,
    orw_shellcode,
    orw_source,
)
from .target import (
    ABI,
    Architecture,
    CallingConvention,
    Endian,
    FunctionPointerModel,
    SUPPORTED_TARGETS,
    Target,
    resolve_target,
)

__all__ = [
    "ABI",
    "Address",
    "AddressResolutionError",
    "Architecture",
    "AssemblyError",
    "CallingConvention",
    "ConstraintError",
    "Endian",
    "ExecutionPolicy",
    "FunctionPointerModel",
    "Image",
    "LibcError",
    "LibcIdentity",
    "LibcImage",
    "Linkage",
    "LLVMAssembler",
    "MemoryAccessError",
    "MemoryRequirement",
    "Mitigations",
    "Payload",
    "PayloadError",
    "PayloadKind",
    "Permission",
    "Relro",
    "RuntimeLayout",
    "SUPPORTED_TARGETS",
    "Target",
    "UnsupportedTargetError",
    "command_shellcode",
    "command_source",
    "exit_shellcode",
    "exit_source",
    "llvm_triple",
    "mmap_stager",
    "mmap_stager_source",
    "orw_shellcode",
    "orw_source",
    "resolve_target",
]
